[workspace]
resolver = "2"

members = [
    "afl-fuzz-clone",
    "dump-corpus",
    "zafl_constants",
    "dump-queue-stats",
    "storfuzz-fuzzbench",
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
