[package]
name = "dump-corpus"
version = "0.1.1"
edition = "2021"

[features]
variable-data-map-size = []

[dependencies]
libafl = {path="../../LibAFL/libafl", features = []}
clap = {version = "4.1.4", features = ["derive"] }
konst = {version = "0.3.5", features = ["parsing"]}